version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/openjdk:11.0.4
    steps:
      - checkout
      #- run: java --version
      - run:
        name: Install dependencies
        command: mvn install
      - run:
        name: Run Tests
        command: mvn run test
